server:
  port: 80
spring:
  application:
    name: zpark-sc-gateway
  cloud:
    gateway:
      routes:
      - id: loginPage-route
        uri: http://localhost:4001
        predicates:
        - Path=/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka